config/routes.rb
Sheeps::Application.routes.draw do
  resources :other_purchases

  resources :users

  resources :removes

  resources :sheep_sellings

  resources :vacinations

  resources :matings

  resources :sheep_purchases

  resources :activities

  resources :lambings

  resources :sheep
  
  resources :sessions, only: [:new, :create]
  
  get "welcome/index"
  
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
    resources :uginuces
get '/', to: 'sheep#statistics'
get 'root', to: 'sheep#statistics'
get '/reports', to: 'reports#index'
get '/report_new', to: 'reports#report'
get '/statistics', to: 'sheep#statistics'

get 'sheeplist', to:'sheep#sheeplist'

end

app/models/uginuce.rb
class Uginuce < ActiveRecord::Base
    belongs_to :sheep
    belongs_to :activity, :dependent => :destroy
end

app/controllers/uginuces_controller.rb
class UginucesController < ApplicationController
  before_action :set_uginuce, only: [:show, :edit, :update, :destroy]
  before_action :check_current_user, only: [:new, :edit, :destroy, :index, :show]
  # GET /uginuces
  # GET /uginuces.json
  def index
    @uginuces = Uginuce.all
    @sheeps = Sheep.all
  end

  # GET /uginuces/1
  # GET /uginuces/1.json
  def show
  end

  # GET /uginuces/new
  def new
    @uginuce = Uginuce.new
        @sheeps = Sheep.all
  end

  # GET /uginuces/1/edit
  def edit
        @sheeps = Sheep.all
  end

  # POST /uginuces
  # POST /uginuces.json
  def create
    @uginuce = Uginuce.new(uginuce_params)
    @sheep = Sheep.find_by id: @uginuce.sheep_id
    @sheep.update status:'uginulo'
    a = Activity.new date: convert_date_to_i(params[:uginuce_date]), a_type: 'uginuce', comment:params[:uginuce_comment], location: 'farma'

    a.uginuce = @uginuce
    respond_to do |format|
      if a.save
        format.html { redirect_to @uginuce, notice: 'Uginuce was successfully created.' }
        format.json { render action: 'show', status: :created, location: @uginuce }
      else
        format.html { render action: 'new' }
        format.json { render json: @uginuce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uginuces/1
  # PATCH/PUT /uginuces/1.json
  def update
    if @uginuce.sheep.id!= params[:uginuce][:sheep_id].to_i
        @old_sheep = Sheep.find_by id: @uginuce.sheep_id
        @old_sheep.update status:'na farmi'
        @new_sheep = Sheep.find_by id: params[:uginuce][:sheep_id]
        @new_sheep.update status:'uginulo'
    end
    
    @uginuce.activity.update date: convert_date_to_i(params[:uginuce_date]), comment:params[:uginuce_comment]
    respond_to do |format|
      if @uginuce.update(uginuce_params)
        format.html { redirect_to @uginuce, notice: 'Uginuce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @uginuce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uginuces/1
  # DELETE /uginuces/1.json
  def destroy
    @uginuce.sheep.update status:'na farmi'
    @uginuce.destroy
    respond_to do |format|
      format.html { redirect_to uginuces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uginuce
      @uginuce = Uginuce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uginuce_params
      params.require(:uginuce).permit(:sheep_id)
    end
end

app/helpers/uginuces_helper.rb
module UginucesHelper
end

app/views/uginuces/_form.html.erb
<%= form_for(@uginuce) do |f| %>
  <% if @uginuce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uginuce.errors.count, "error") %> prohibited this uginuce from being saved:</h2>

      <ul>
      <% @uginuce.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br><br>
  <strong> Datum</strong> <input type="text" data-behaviour='datepicker' data-format="YYYY/MM/DD" name='uginuce_date' <% if @uginuce.activity!= nil %>value='<%=@uginuce.activity.show_date %>'<%end%>>
   
  uginula ovca:
  <select name='[uginuce][sheep_id]' class = 'select' style='width: 150px'>
    <%@sheeps.each do |s|%>
      <% if @uginuce.sheep!=nil and s.id== @uginuce.sheep.id%>
          <option value='<%= s.id %>' selected><%= s.code%> <%=  s.nickname %></option>
      <% else%>
          <option value='<%= s.id %>'><%= s.code%> <%=  s.nickname %></option>
      <% end %>
    <% end %>
  </select>
  <br><br>
  <textarea class="form-control" rows="3" name='uginuce_comment'  placeholder="Unesi razlog i opste zapazanje..."><% if @uginuce.activity!= nil %><%= @uginuce.activity.comment %><% end %></textarea><br>
  
  <div class="actions">
    <%= f.submit :Snimi, class:"btn btn-primary" %>
    <%= link_to 'Back', uginuces_path, class:"btn btn-default"  %>
      
  </div>
<% end %>

app/views/uginuces/edit.html.erb
<h1>Izmeni uginuce</h1>

<%= render 'form' %>

app/views/uginuces/index.html.erb
<h1 class='page_title'>Lista uginuca</h1>
<br>
<table class="table table-hover">
  <thead>
    <tr class='danger'>
      <th class="col-sm-2">Datum</th>
      <th class="col-sm-1">ovca oznaka</th>
      <th class="col-sm-1">ovca nadimak</th>
      <th class="col-sm-3">razlog</th>
      <th class="col-sm-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @uginuces.each do |u| %>
      <tr>
        <td><%= u.activity.show_date %></td>
        <td><%= u.sheep.code %></td>
        <td><%= u.sheep.nickname %></td>
        <td><strong><%= u.activity.comment %></strong></td>
        <td><%= link_to 'prikazi', '/uginuces/'+u.id.to_s, class:"btn btn-primary" %></td>
     <!--   <td></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if not current_user.nil? %>
      <%= link_to 'novo uginuce', new_uginuce_path, class:"btn btn-primary" %>
<% end %>

app/views/uginuces/new.html.erb
<h1 class='page_title'>Novo uginuce</h1>

<%= render 'form' %>

app/views/uginuces/show.html.erb
<p id="notice"><%= notice %></p>
<h2><strong>Dana </strong><%= @uginuce.activity.show_date%></h2>
<h3>
  Uginula je ovca: <%= @uginuce.sheep.code%> <%= @uginuce.sheep.nickname%>
</h3>

<br>
<textarea class="form-control" rows="3" name='comment' readonly='true'  placeholder="Nije bilo zapaznja..."><%= @uginuce.activity.comment %></textarea><br>

<% if not current_user.nil? %>
      <%= link_to 'Izmeni', edit_uginuce_path(@uginuce), class:"btn btn-primary" %>
      <%= link_to 'Izbrisi', @uginuce , method: :delete, data: { confirm: 'Jesi li siguran?' }, class:"btn btn-danger" %>
<% end %>
<%= link_to 'Nazad', uginuces_path, class:"btn btn-default" %>