config/routes.rb
Sheeps::Application.routes.draw do
  resources :other_purchases

  resources :users

  resources :removes

  resources :sheep_sellings

  resources :vacinations

  resources :matings

  resources :sheep_purchases

  resources :activities

  resources :lambings

  resources :sheep
  
  resources :sessions, only: [:new, :create]
  
  get "welcome/index"
  
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
    resources :uginuces
get '/', to: 'sheep#statistics'
get 'root', to: 'sheep#statistics'
get '/reports', to: 'reports#index'
get '/report_new', to: 'reports#report'
get '/statistics', to: 'sheep#statistics'

get 'sheeplist', to:'sheep#sheeplist'

end

app/models/mating.rb
class Mating < ActiveRecord::Base
end

app/controllers/matings_controller.rb
class MatingsController < ApplicationController
  before_action :set_mating, only: [:show, :edit, :update, :destroy]
  before_action :check_current_user, only: [:new, :edit, :destroy, :index, :show]

  # GET /matings
  # GET /matings.json
  def index
    @matings = Mating.all
  end

  # GET /matings/1
  # GET /matings/1.json
  def show
  end

  # GET /matings/new
  def new
    @mating = Mating.new
  end

  # GET /matings/1/edit
  def edit
  end

  # POST /matings
  # POST /matings.json
  def create
    @mating = Mating.new(mating_params)

    respond_to do |format|
      if @mating.save
        format.html { redirect_to @mating, notice: 'Mating was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mating }
      else
        format.html { render action: 'new' }
        format.json { render json: @mating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matings/1
  # PATCH/PUT /matings/1.json
  def update
    respond_to do |format|
      if @mating.update(mating_params)
        format.html { redirect_to @mating, notice: 'Mating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matings/1
  # DELETE /matings/1.json
  def destroy
    @mating.destroy
    respond_to do |format|
      format.html { redirect_to matings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mating
      @mating = Mating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mating_params
      params.require(:mating).permit(:male_id, :price, :activity_id, :sheep_id, :comment)
    end
end

app/helpers/matings_helper.rb
module MatingsHelper
end

app/views/matings/_form.html.erb
<%= form_for(@mating) do |f| %>
  <% if @mating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mating.errors.count, "error") %> prohibited this mating from being saved:</h2>

      <ul>
      <% @mating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :male_id %><br>
    <%= f.number_field :male_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :activity_id %><br>
    <%= f.number_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :sheep_id %><br>
    <%= f.number_field :sheep_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matings/edit.html.erb
<h1>Editing mating</h1>

<%= render 'form' %>

<%= link_to 'Show', @mating %> |
<%= link_to 'Back', matings_path %>

app/views/matings/index.html.erb
<h1>Listing matings</h1>

<table>
  <thead>
    <tr>
      <th>Male</th>
      <th>Price</th>
      <th>Activity</th>
      <th>Sheep</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matings.each do |mating| %>
      <tr>
        <td><%= mating.male_id %></td>
        <td><%= mating.price %></td>
        <td><%= mating.activity_id %></td>
        <td><%= mating.sheep_id %></td>
        <td><%= mating.comment %></td>
        <td><%= link_to 'Show', mating %></td>
        <td><%= link_to 'Edit', edit_mating_path(mating) %></td>
        <td><%= link_to 'Destroy', mating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mating', new_mating_path %>

app/views/matings/new.html.erb
<h1>New mating</h1>

<%= render 'form' %>

<%= link_to 'Back', matings_path %>

app/views/matings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Male:</strong>
  <%= @mating.male_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @mating.price %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @mating.activity_id %>
</p>

<p>
  <strong>Sheep:</strong>
  <%= @mating.sheep_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @mating.comment %>
</p>

<%= link_to 'Edit', edit_mating_path(@mating) %> |
<%= link_to 'Back', matings_path %>