config/routes.rb
Sheeps::Application.routes.draw do
  resources :other_purchases

  resources :users

  resources :removes

  resources :sheep_sellings

  resources :vacinations

  resources :matings

  resources :sheep_purchases

  resources :activities

  resources :lambings

  resources :sheep
  
  resources :sessions, only: [:new, :create]
  
  get "welcome/index"
  
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
    resources :uginuces
get '/', to: 'sheep#statistics'
get 'root', to: 'sheep#statistics'
get '/reports', to: 'reports#index'
get '/report_new', to: 'reports#report'
get '/statistics', to: 'sheep#statistics'

get 'sheeplist', to:'sheep#sheeplist'

end

app/models/remove.rb
class Remove < ActiveRecord::Base
end

app/controllers/removes_controller.rb
class RemovesController < ApplicationController
  before_action :set_remove, only: [:show, :edit, :update, :destroy]

  # GET /removes
  # GET /removes.json
  def index
    @removes = Remove.all
  end

  # GET /removes/1
  # GET /removes/1.json
  def show
  end

  # GET /removes/new
  def new
    @remove = Remove.new
  end

  # GET /removes/1/edit
  def edit
  end

  # POST /removes
  # POST /removes.json
  def create
    @remove = Remove.new(remove_params)

    respond_to do |format|
      if @remove.save
        format.html { redirect_to @remove, notice: 'Remove was successfully created.' }
        format.json { render action: 'show', status: :created, location: @remove }
      else
        format.html { render action: 'new' }
        format.json { render json: @remove.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /removes/1
  # PATCH/PUT /removes/1.json
  def update
    respond_to do |format|
      if @remove.update(remove_params)
        format.html { redirect_to @remove, notice: 'Remove was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @remove.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /removes/1
  # DELETE /removes/1.json
  def destroy
    @remove.destroy
    respond_to do |format|
      format.html { redirect_to removes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remove
      @remove = Remove.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remove_params
      params.require(:remove).permit(:death)
    end
end

app/helpers/removes_helper.rb
module RemovesHelper
end

app/views/removes/_form.html.erb
<%= form_for(@remove) do |f| %>
  <% if @remove.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@remove.errors.count, "error") %> prohibited this remove from being saved:</h2>

      <ul>
      <% @remove.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :death %><br>
    <%= f.text_field :death %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/removes/edit.html.erb
<h1>Editing remove</h1>

<%= render 'form' %>

<%= link_to 'Show', @remove %> |
<%= link_to 'Back', removes_path %>

app/views/removes/index.html.erb
<h1>Listing removes</h1>

<table>
  <thead>
    <tr>
      <th>Death</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @removes.each do |remove| %>
      <tr>
        <td><%= remove.death %></td>
        <td><%= link_to 'Show', remove %></td>
        <td><%= link_to 'Edit', edit_remove_path(remove) %></td>
        <td><%= link_to 'Destroy', remove, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remove', new_remove_path %>

app/views/removes/new.html.erb
<h1>New remove</h1>

<%= render 'form' %>

<%= link_to 'Back', removes_path %>

app/views/removes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Death:</strong>
  <%= @remove.death %>
</p>

<%= link_to 'Edit', edit_remove_path(@remove) %> |
<%= link_to 'Back', removes_path %>